CREATE OR REPLACE 
PACKAGE QU8 AS 

 FUNCTION AVERAGE_PROJ_COST( p_cust_no NUMBER ) RETURN NUMBER ;
 FUNCTION COST_OF_PROJECT( p_proj_no NUMBER ) RETURN NUMBER ;
 FUNCTION NO_OF_PROJECTS( p_cust_no NUMBER ) RETURN NUMBER ;

END QU8;